name: Build Daemons

on:
  push:
    paths:
      - 'Makefile'
      - 'daemon/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build daemon binaries
      run: |
        sudo apt update && sudo apt install -y build-essential
        make
        file build/*
